"use client";

import React from "react";

import { usePathname, useRouter } from "next/navigation";
import Dashboard from "./assets/dashboard.svg";
import UserManagement from "./assets/user.svg";
import ReportManagement from "./assets/report-management.svg";
import PaymentMangement from "./assets/payment.svg";

import AutoGeneratedReports from "./assets/auto-generated-reports.svg";
import ContactUsSubmission from "./assets/contact-us-submission.svg";
import TheWall from "./assets/the-wall.svg";

import PushNotification from "./assets/push-notification.svg";
import Settings from "./assets/settings.svg";

import Logout from "./assets/logout.svg";




interface SidebarItemConfig {
  icon: React.FunctionComponent<React.SVGProps<SVGSVGElement>>;
  title: string;
  path: string;
}

interface SidebarItemProps extends SidebarItemConfig {
  color: string;
  isActive: boolean;
  onClick: () => void;
}

const sidebarItems: SidebarItemConfig[] = [
  { icon: Dashboard, title: "Dashboard", path: "/dashboard" },
  { icon: UserManagement, title: "User Management", path: "/user-management" },
  { icon: ReportManagement, title: "Report Management", path: "/report-management" },
  { icon: PaymentMangement, title: "Payment Management", path: "/payment-management" },
  { icon: AutoGeneratedReports, title: "Auto Generated Reports", path: "/auto-generated-reports" },
  { icon: ContactUsSubmission, title: "Contact Us Submission", path: "/contact-us-submission" },
  { icon: TheWall, title: "The Wall", path: "/the-wall" },
  { icon: Logout, title: "Log out", path: "/" },
];

export default function Sidebar() {
  const pathname = usePathname();
  const router = useRouter();

  return (
    <div className="rounded-[16px] overflow-hidden border border-[#EAEAEA] bg-white max-w-75 ">
      {sidebarItems.map((item, index) => {
        const isActive = pathname === item.path;
        const isLogout = item.title === "Log out";

        const color = isLogout ? "#B50F02" : isActive ? "#5E189D" : "#4D4D4D";

        return (
          <SidebarItem
            key={index}
            icon={item.icon}
            title={item.title}
            path={item.path}
            color={color}
            isActive={isActive}
            onClick={() => router.push(item.path)}
          />
        );
      })}
    </div>
  );
}

function SidebarItem({
  icon: Icon,
  title,
  color,
  isActive,
  onClick,
}: SidebarItemProps) {
  return (
    <div
      className={`flex gap-[10px] px-10 py-6 cursor-pointer ${
        isActive ? "bg-[#F4EBFF]" : ""
      }`}
      onClick={onClick}
    >
      <Icon fill={color} width={24} height={24} />
      <p
        className={`sm:hidden lg:block font-medium text-base font-[Poppins] leading-normal `}
        style={{ color }}
      >
        {title}
      </p>
    </div>
  );
}
